project:
  type: website

website:
  title: "The No Fluff Traveler"
  favicon: images/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Reviews
        menu:
          - href: posts/misool.qmd
            text: Misool Eco Resort
          - href: posts/morgans-rock.qmd
            text: Morgan's Rock
      - href: field-notes.qmd
        text: Field Notes
      - href: faq.qmd
        text: FAQ
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css